import Head from 'next/head';
import { useState, useEffect, useRef } from 'react';
import { Header } from '../components';

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="relative w-screen h-screen bg-[#152A21] text-white">
        <Header />
      </main>
    </>
  );
}
