import Head from 'next/head';
import { Header, Marquee } from '../components';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative w-screen h-screen flex flex-col justify-center items-center">
        <Header />
        <Marquee title="EXPLORE THE ARCHIVES" seperator duration={12} />
      </div>
    </div>
  );
}
